name: Build on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu_build:
    name: Build on Ubuntu with Swift ${{matrix.swift}}
    strategy:
      matrix:
        swift: ["6.0", "6.0.3"]
    runs-on: ubuntu-latest
    container: 
      image: swift:${{matrix.swift}}
    steps:          
      - name: Checkout
        uses: actions/checkout@master

      - name: Swift version
        run: swift --version
        
      - name: Swift build
        run: swift build -c release
