name: Test on Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
   ubuntu-test:
     name: Run tests on Ubuntu with CouchDB ${{ matrix.couchdb }}
     strategy:
       fail-fast: false
       matrix:
         couchdb: [latest, "3.3", "3.2", "3.1"]
     runs-on: ubuntu-latest
     services:
       swift:
         image: swift:latest
     steps:
       - name: Start CouchDB
         uses: iamssen/couchdb-github-action@master
         with:
           couchdb-version: ${{ matrix.couchdb }}
       - name: Checkout
         uses: actions/checkout@master
       - name: Swift version
         run: |
           swift --version
       - name: Test endpoint
         run: |
           curl -sS -f http://127.0.0.1:5984/
       - name: Test authorization
         run: |
           curl -X POST -H "Content-Type: application/json; charset=utf-8" -d '{"name": "admin", "password": "password"}' http://127.0.0.1:5984/_session
       - name: Swift test
         run: COUCHDB_PASS=password swift test 
